# Solving System of Linear Equations using Elimination Method
Recall our equation:
\begin{align}
-x_{1} + 3x_{2} &=7 \\ 3x_{1} + 2x_{2} &=1 \tag{1} \end{align}

In [2]:
import numpy as np
A = np.array([[-1, 3],[3, 2]], dtype = np.dtype(float))
b = np.array([7, 1], dtype = np.dtype(float))

Now, for Elimination Method we stack the matrix.

In [6]:
A_system = np.hstack((A, b.reshape(2, 1)))
print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


To Solve, we copy the oringal one first

In [7]:
A_system_res = A_system.copy()

Multiply the first row by 3 and add it to the second row, then store it in the second row of the system

In [8]:
A_system_res[1] = A_system_res[0] * 3 + A_system_res[1]
print(A_system_res)

[[-1.  3.  7.]
 [ 0. 11. 22.]]


Multiiply second row by 1/11

In [10]:
A_system_res[1] = 1/11 * A_system_res[1]
print(A_system_res)

[[-1.  3.  7.]
 [ 0.  1.  2.]]
