#  Definition of Matrix Multiplication

If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, the matrix product $C = AB$ (denoted without multiplication signs or dots) is defined to be the $m \times p$ matrix such that 
$c_{ij}=a_{i1}b_{1j}+a_{i2}b_{2j}+\ldots+a_{in}b_{nj}=\sum_{k=1}^{n} a_{ik}b_{kj}, \tag{4}$

where $a_{ik}$ are the elements of matrix $A$, $b_{kj}$ are the elements of matrix $B$, and $i = 1, \ldots, m$, $k=1, \ldots, n$, $j = 1, \ldots, p$. In other words, $c_{ij}$ is the dot product of the $i$-th row of $A$ and the $j$-th column of $B$.

In [ ]:
import numpy as np
A = np.array([[4,9,9],[9,1,6],[9,2,3]])
print("Matrix A is a (3 x 3) \n", A)

B = np.array([[2,2],[5,7],[4,4]])
print("Matrix A is a (3 x 2) \n", B)

now multiplying A and B using `np.matmul()` or `@`

In [3]:
np.matmul(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [4]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

### Matrix Convention and Broadcasting

Mathemically, Matrix multiplication can only occur if the `column of matrix A` correspond to the `row of matrix B`

Let's switch the above matrix and see what happens. $BA$

In [6]:
try:
    np.matmul(B,A)
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


`np.dot()` would also yield the same output as `np.matmul()`

In [7]:
np.dot(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

What actually happens is what is called **broadcasting** in Python: `NumPy` broadcasts this dot product operation to all rows and all columns, you get the resultant product matrix.