## 1 - Transformations

A **transformation** is a function from one vector space to another that respects the underlying (linear) structure of each vector space. Referring to a specific transformation, you can use a symbol, such as $T$. Specifying the spaces containing the input and output vectors, e.g. $\mathbb{R}^2$ and $\mathbb{R}^3$, you can write $T: \mathbb{R}^2 \rightarrow \mathbb{R}^3$. Transforming vector $v \in \mathbb{R}^2$ into the vector $w\in\mathbb{R}^3$ by the transformation $T$, you can use the notation $T(v)=w$ and read it as "*T of v equals to w*" or "*vector w is an **image** of vector v with the transformation T*".

The following Python function corresponds to the transformation $T: \mathbb{R}^2 \rightarrow \mathbb{R}^3$ with the following symbolic formula:
$$T\begin{pmatrix}
          \begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}\end{pmatrix}=
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix}
          \tag{1}
          $$

In [1]:
import numpy as np

In [2]:
def T(v):
    w = np.zeros((3,1))
    w[0,0] = 3 * v[0,0]
    w[2,0] = -2 * v[1,0]
    return w

v = np.array([[3], [5]])
w = T(v)

print("Original vector: \n", v, "\n\n Result of the transformation: \n", w)
    

Original vector: 
 [[3]
 [5]] 

 Result of the transformation: 
 [[  9.]
 [  0.]
 [-10.]]


<a name='2'></a>
## 2 - Linear Transformations

A transformation $T$ is said to be **linear** if the following two properties are true for any scalar $k$, and any input vectors $u$ and $v$:

1. $T(kv)=kT(v)$,
2. $T(u+v)=T(u)+T(v)$.

In the example above $T$ is a linear transformation:

$$T (kv) =
          T \begin{pmatrix}\begin{bmatrix}
          kv_1 \\
          kv_2
          \end{bmatrix}\end{pmatrix} = 
          \begin{bmatrix}
           3kv_1 \\
           0 \\
           -2kv_2
          \end{bmatrix} =
          k\begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix} = 
          kT(v),\tag{2}$$
          
$$T (u+v) =
          T \begin{pmatrix}\begin{bmatrix}
          u_1 + v_1 \\
          u_2 + v_2
          \end{bmatrix}\end{pmatrix} = 
          \begin{bmatrix}
           3(u_1+v_1) \\
           0 \\
           -2(u_2+v_2)
          \end{bmatrix} = 
          \begin{bmatrix}
           3u_1 \\
           0 \\
           -2u_2
          \end{bmatrix} +
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix} = 
          T(u)+T(v).\tag{3}$$

In [3]:
u = np.array([[1],[-2]])
v = np.array([[2], [4]])
k = 7

print("T(k*v): \n", T(k*v), "\n K*T(v):\n", k*T(v), "\n\n")

T(k*v): 
 [[ 42.]
 [  0.]
 [-56.]] 
 K*T(v):
 [[ 42.]
 [  0.]
 [-56.]] 




In [ ]:
print ("T(u+v): \n", T(u+v), "\n T(u) + T(v)\n"