# Row Reduction and Solution of the linear System
Recall our equation:

\begin{cases}
4x_{1}-3x_{2}+x_{3} &= 10 \\ 
2x_{1}+x_{2}+3x_{3} &= 0 \\
-x_{1}+2x_{2}-5x_{3} &= 17 \tag{1} \end{cases}

In [3]:
import numpy as np
A = np.array([[4, -3, 1],[2, 1, 3],[-1, 2, -5]], dtype = np.dtype(float))
b = np.array([-10, 0, 17], dtype = np.dtype(float))

print("Matrix A:\n", A)
print("Array b: \n", b)

Matrix A:
 [[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
Array b: 
 [-10.   0.  17.]


In [4]:
#stacking
A_system = np.hstack((A, b.reshape((3, 1))))
print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


### Recall our functions:

In [5]:
def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

def AddRow(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] =  (row_num_1_multiple * M_new[row_num_1]) + M_new[row_num_2]
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

Now to solve of matrix using row reduction, we start by swapping the rows first. It is convenient to have 1 or -1 in the first element of the first row.

In [8]:
A_ref = SwapRows(A_system, 0, 2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


We've swapped the rows. Next goal is to make the first element in row 2 to be zero. We do this by multiplying row 1 by 2 and adding it to row 2

In [10]:
A_ref = AddRow(A_ref, 0, 1, 2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  4.  -3.   1. -10.]]


The next goal is to make 4 on the third row become 0. we do this by Adding row 1 multiplied with 4 to row 3, and storing it in row 3

In [11]:
A_ref = AddRow(A_ref, 0, 2, 4)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   5. -19.  58.]]


The next goal is to turn the 5 in the third row into a 0. We do this by Adding the second row multiplied by -1 to row three

In [12]:
A_ref = AddRow(A_ref, 1, 2, -1)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   0. -12.  24.]]


Now, it's to find the value of $x_3$ from the third row as it corresponds to the equation $-12x_3 = 24$ so let's divide the 3rd row by -12 by multiplying with -1/12

In [13]:
A_ref = MultiplyRow(A_ref, 2, -1/12)
print(A_ref)

[[-1.  2. -5. 17.]
 [ 0.  5. -7. 34.]
 [-0. -0.  1. -2.]]


Now we know what our $x_3$ is. The second row corresponds to $5x_2 - 7x_3 = 34$ and the first row, $-x_1 + 2x_2 - 5x_3 = 17$
Referring to the element of the matrix, we can find $x_2, x_3$

In [15]:
x_3 = -2.0
x_2 = ((A_ref[1, 3] - A_ref[1, 2] * x_3) / A_ref[1, 1])
x_1 = ((A_ref[0, 3] - A_ref[0, 2] * x_3 - A_ref[0, 1] * 2) / A_ref[0, 0])
print(x_3, x_2, x_1)

-2.0 4.0 -3.0
