# System of Linear Equations with Infinite Number of Solutions

Given the equation:
\begin{cases}
x_{1}+x_{2}+x_{3} &= 2 \\ 
x_{2}-3x_{3} &= 1 \\
2x_{1}+x_{2}+5x_{3} &= 3 \tag{3}\end{cases}

In [14]:
import numpy as np

A = np.array([[1, 1, 1],[0, 1, -3],[2, 1, 5]], dtype = np.dtype(float))
b = np.array([2, 1, 3], dtype = np.dtype(float))

print("Matrix A:\n", A)
print("Array b: \n", b)

Matrix A:
 [[ 1.  1.  1.]
 [ 0.  1. -3.]
 [ 2.  1.  5.]]
Array b: 
 [2. 1. 3.]


Now for us to check if the this matrix has a unique solution, we find its determinant. 

In [15]:
D = np.linalg.det(A)
print(f"Determinant of Matrix is: {D:.2f}")

Determinant of Matrix is: 0.00


So we see that the determinant is zero. This means one of two things: The matrix or the linear equation has **no solution**; or it has **infinite solutions**. To find which exactly it is from the two options. we can use the **Row Reduction**

using Row Reduction, we have to stack the matrix A and B together first

### Recall our functions:

In [16]:
def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

def AddRow(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] =  (row_num_1_multiple * M_new[row_num_1]) + M_new[row_num_2]
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

In [17]:
A_sys = np.hstack((A, b.reshape((3,1))))
print(A_sys)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  3.]]


Now, our goal is to eliminate the 2 in the third array. We achieve this by Adding row 1 multiplied by -2 to array 3.

In [18]:
A_ref = AddRow(A_sys, 0, 2, -2)
print(A_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -1.]]


Add row 2 to row 3 next

In [19]:
A_ref = AddRow(A_ref, 1, 2, 1)
print(A_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0.  0.]]


Here, the last row of the matrix corresponds to the 0 = 0. Meaning that the linear system has infinite number of solutions