# Solving Linear System with 3 Variables
Given the equation:
\begin{cases}
4x_{1}-3x_{2}+x_{3} &= 10 \\ 
2x_{1}+x_{2}+3x_{3} &= 0 \\
-x_{1}+2x_{2}-5x_{3} &= 17 \tag{1} \end{cases}

In [2]:
import numpy as np

In [11]:
A = np.array([[4, -3, 1],[2, 1, 3],[-1, 2, -5]], dtype = np.dtype(float))
b = np.array([-10, 0, 17], dtype = np.dtype(float))

print("Matrix A:\n", A)
print("Array b: \n", b)

Matrix A:
 [[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
Array b: 
 [-10.   0.  17.]


To check the dimension of A and b

In [7]:
print("shape of matrix A: ", np.shape(A))
print("shape of array b: ", np.shape(b))

shape of matrix A:  (3, 3)
shape of array b:  (3,)


To Solve

In [12]:
x = np.linalg.solve(A, b)
print(f"solution: {x}")

solution: [ 1.  4. -2.]


In [ ]:
# Evaluation The Determinant of t