# Solving System of Linear Equation using Row Reduction
Recall the previous equation:
\begin{cases}
4x_{1}-3x_{2}+x_{3} &= 10 \\ 
2x_{1}+x_{2}+3x_{3} &= 0 \\
-x_{1}+2x_{2}-5x_{3} &= 17 \tag{1} \end{cases}

We will create a matrix for it and then unify the matrix using `np.hstack()` function

In [2]:
import numpy as np

In [3]:
A = np.array([[4, -3, 1],[2, 1, 3],[-1, 2, -5]], dtype = np.dtype(float))
b = np.array([-10, 0, 17], dtype = np.dtype(float))

print("Matrix A:\n", A)
print("Array b: \n", b)

Matrix A:
 [[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
Array b: 
 [-10.   0.  17.]


Unifying the matrix:

In [13]:
A_system = np.hstack((A, b.reshape((3, 1))))
print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


## Functions of Elementary Operations
Elementary Operations which do not change the solution of a linear system

- Multiply any row by a non-zero number
- Add two rows and exhange one of the original rows with the result of the addition
- Swap rows

### Multiply Row Function

In [16]:
def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

To test:

In [19]:
print("Original Matrix: \n", A_system)
print("\nMatrix after 3rd row is multipied by 2:\n", MultiplyRow(A_system, 2, 2))

Original Matrix: 
 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after 3rd row is multipied by 2:
 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10.  34.]]


### Add Row Function

In [26]:
def AddRow(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] =  (row_num_1_multiple * M_new[row_num_1]) + M_new[row_num_2]
    return M_new

To test:

In [27]:
print("Original Matrix: \n", A_system)
print("\n MAtrix after exhange of the third row with the sum of itself and second row multiplied by 1/2:\n", AddRow(A_system, 1, 2, 1/2))

Original Matrix: 
 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

 MAtrix after exhange of the third row with the sum of itself and second row multiplied by 1/2:
 [[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]


### Swap Function

In [34]:
def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

To test:

In [35]:
print("Original Matrix: \n", A_system)
print("\n Matrix after swapping third row with second row:\n", SwapRows(A_system, 1, 2))

Original Matrix: 
 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

 Matrix after swapping third row with second row:
 [[  4.  -3.   1. -10.]
 [ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]]
