# Row Reduction and Solution of the linear System
Recall our equation:

\begin{cases}
4x_{1}-3x_{2}+x_{3} &= 10 \\ 
2x_{1}+x_{2}+3x_{3} &= 0 \\
-x_{1}+2x_{2}-5x_{3} &= 17 \tag{1} \end{cases}

In [3]:
import numpy as np
A = np.array([[4, -3, 1],[2, 1, 3],[-1, 2, -5]], dtype = np.dtype(float))
b = np.array([-10, 0, 17], dtype = np.dtype(float))

print("Matrix A:\n", A)
print("Array b: \n", b)

Matrix A:
 [[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
Array b: 
 [-10.   0.  17.]


In [4]:
#stacking
A_system = np.hstack((A, b.reshape((3, 1))))
print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


### Recall our functions:

In [5]:
def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

def AddRow(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] =  (row_num_1_multiple * M_new[row_num_1]) + M_new[row_num_2]
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

Now to solve of matrix using row reduction, we start by swapping the rows first. It is convenient to have 1 or -1 in the first element of the first row.

In [8]:
A_ref = SwapRows(A_system, 0, 2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]
