# System of Linear Equations with No Solution

Given this equation:
\begin{cases}
x_{1}+x_{2}+x_{3} &= 2 \\ 
x_{2}-3x_{3} &= 1 \\
2x_{1}+x_{2}+5x_{3} &= 0 \tag{2}\end{cases}

In [9]:
import numpy as np

A = np.array([[1, 1, 1],[0, 1, -3],[2, 1, 5]], dtype = np.dtype(float))
b = np.array([2, 1, 0], dtype = np.dtype(float))

print("Matrix A:\n", A)
print("Array b: \n", b)

Matrix A:
 [[ 1.  1.  1.]
 [ 0.  1. -3.]
 [ 2.  1.  5.]]
Array b: 
 [2. 1. 0.]


Now for us to check if the this matrix has a unique solution, we find its determinant. 

In [10]:
D = np.linalg.det(A)
print(f"Determinant of Matrix is: {D:.2f}")

Determinant of Matrix is: 0.00


So we see that the determinant is zero. This means one of two things: The matrix or the linear equation has **no solution**; or it has **infinite solutions**. To find which exactly it is from the two options. we can use the Row 