# System of Linear Equations with No Solution

Given this equation:
\begin{cases}
x_{1}+x_{2}+x_{3} &= 2 \\ 
x_{2}-3x_{3} &= 1 \\
2x_{1}+x_{2}+5x_{3} &= 0 \tag{2}\end{cases}

In [9]:
import numpy as np

A = np.array([[1, 1, 1],[0, 1, -3],[2, 1, 5]], dtype = np.dtype(float))
b = np.array([2, 1, 0], dtype = np.dtype(float))

print("Matrix A:\n", A)
print("Array b: \n", b)

Matrix A:
 [[ 1.  1.  1.]
 [ 0.  1. -3.]
 [ 2.  1.  5.]]
Array b: 
 [2. 1. 0.]


Now for us to check if the this matrix has a unique solution, we find its determinant. 

In [10]:
D = np.linalg.det(A)
print(f"Determinant of Matrix is: {D:.2f}")

Determinant of Matrix is: 0.00


So we see that the determinant is zero. This means one of two things: The matrix or the linear equation has **no solution**; or it has **infinite solutions**. To find which exactly it is from the two options. we can use the **Row Reduction**

using Row Reduction, we have to stack the matrix A and B together first

In [24]:
A_sys = np.hstack((A, b.reshape((3,1))))
print(A_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  0.]]


### Recall our functions:

In [14]:
def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

def AddRow(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] =  (row_num_1_multiple * M_new[row_num_1]) + M_new[row_num_2]
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

Now, our goal is to eliminate the 2 in the third array. We achieve this by Adding row 1 multiplied by -2 to array 3.

In [25]:
A_ref = AddRow(A_sys, 0, 2, -2)
print(A_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -4.]]


Add row 2 to row 3 next

In [26]:
A_ref = AddRow(A_ref, 1, 2, 1)
print(A_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0. -3.]]


so we see that the last row will correspond to 0 = -3 which has no solution. Thus this whole linear system has not solution.